apiVersion: v1
kind: Service
metadata:
  name: chatify-scylla
  namespace: chatify
  labels:
    app.kubernetes.io/name: chatify-scylla
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: chatify
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
      protocol: TCP
    - name: cql-ssl
      port: 9142
      targetPort: 9142
      protocol: TCP
    - name: thrift
      port: 9160
      targetPort: 9160
      protocol: TCP
    - name: jmx
      port: 7199
      targetPort: 7199
      protocol: TCP
    - name: prometheus
      port: 9180
      targetPort: 9180
      protocol: TCP
  selector:
    app.kubernetes.io/name: chatify-scylla
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: chatify
---
apiVersion: v1
kind: Service
metadata:
  name: chatify-scylla-nodeport
  namespace: chatify
  labels:
    app.kubernetes.io/name: chatify-scylla
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: chatify
    app.kubernetes.io/managed-by: kubectl
spec:
  type: NodePort
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
      nodePort: 30042
      protocol: TCP
  selector:
    app.kubernetes.io/name: chatify-scylla
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: chatify
